server:
  port: 8082
  
spring:
  application:
    name: RAILWAY-TRAIN-SERVICES
    
eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      